services:
  postgres:
    container_name: postgres_e_commerce_db
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - "e-commerce-postgres-data:/var/lib/postgresql/data"

  api-e-commerce:
    container_name: e-commerce-backend
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - ${API_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
    environment:
      - API_PORT=${API_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
    volumes:
      - ./:/app
    
  dozzle:
    image: amir20/dozzle:v5.7.3
    container_name: dozzle
    ports:
      - "${DOZZLE_HOST_PORT}:8080"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_BASE: /dozzle

volumes:
  e-commerce-postgres-data: {}
