definitions:
  lib.Tokens:
    properties:
      refreshToken:
        type: string
      refreshTokenExp:
        type: integer
      token:
        type: string
      tokenExp:
        type: integer
    type: object
  service.LoginUserPayload:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  service.RegisterUserPayload:
    properties:
      age:
        minimum: 1
        type: integer
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      middlename:
        type: string
      password:
        type: string
    required:
    - age
    - email
    - firstname
    - lastname
    - password
    type: object
  utils.ResUser:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: prachurjyagogoi123@gmail.com
  description: This is a dummy backend for an ecommerce store.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: E-Commerce Backend API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: API for user login using email and password
      parameters:
      - description: Login credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.LoginUserPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lib.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResUser'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResUser'
      summary: User Login
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: API for registering users
      parameters:
      - description: Register user payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.RegisterUserPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.ResUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResUser'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResUser'
      summary: User Register
      tags:
      - Auth
  /renew-access-token:
    get:
      consumes:
      - application/json
      description: API for renewing the access token. Make sure to provide the refresh
        token to get the new tokens
      parameters:
      - description: Bearer refreshToken
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/lib.Tokens'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ResUser'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResUser'
      summary: Renew Access Token
      tags:
      - Auth
swagger: "2.0"
